### ISSUE TITLE
Spike: Ensure that S3 buckets have cross-region replication enabled

### ISSUE THREAD

**Issue by pete-j-g** [ministryofjustice/modernisation-platform#1054]
## User Story

As a… modernisation platform engineer
I need to… enable cross-region replication of core infrastructure S3 buckets
So that… configuration of the platform is aligned with best practices

## Value

Cross-region replication of S3 buckets, would align the configuration with best practices and ensure that data is accessible if primary region encounters operational issues.

## Questions / Assumptions

eu-west-2 is the primary region. A suitable replica region will need to be identified.

## Definition of done

- [ ] Findings and potential pattern documented
- [ ] PoC example deployed
- [ ] another team member has reviewed
- [ ] tests are green

## Reference
[CKV_AWS_144](https://docs.bridgecrew.io/docs/ensure-that-s3-bucket-has-cross-region-replication-enabled)
[[PCI.S3.3] S3 buckets should have cross-region replication enabled](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html#pcidss-s3-3)

**Comment by gfou-al** [comment]
As part of this task, we also need to remove `checkov_exclude: CKV_GIT_1,CKV_AWS_144` from the bastion module https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/4/files See also https://docs.bridgecrew.io/docs/ensure-that-s3-bucket-has-cross-region-replication-enabled

**Comment by gfou-al** [comment]
As discussed today with Piotr, Adrian and Seb, I will try to enable replication on the bastion module and submit a PR for review and consideration. This could serve as an example configuration across the mod platform.

Some questions/concerns:

- Do we have one common replication bucket used across all the other buckets?
- The linting tool might still warn about the replication of the replication bucket because it might not be able to separate it from a regular (non-replica) bucket
- S3 has redundancy built in, so replication in this case might be only useful in limited cases where there is some sort of regional temporal network outage and we want to access the bastion logs. On the other hand, the user public keys, which are also stored in the S3 bucket, might not be considered important.

**Comment by gfou-al** [comment]
# Update for the bastion module

- The terraform module supports cross-region replication as an optional configuration: https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket Anywhere we need to use cross-region replication, we should use the terraform module.
- Enabling cross-region replication for the bastion module might be an overkill. This seems more like a best practice to make Jeff Bezos richer. Looking at the use cases provided by Amazon https://aws.amazon.com/s3/features/replication/ none of them seems relevant to our bastion logs. Besides, the `checkov_exclude: CKV_AWS_144` needs to be in place anyway because checkov will require replication for the replication bucket as it cannot separate it from the regular non-replication bucket.
- The bastion module could use the s3-bucket module, however, there is no imminent need for that. If there is any customisation down the line, then we should implement it on the s3-bucket module and use the s3-bucket module from the bastion module.

**Comment by davidkelliott** [comment]
This has been completed for the terraform state bucket in https://github.com/ministryofjustice/modernisation-platform/pull/1081
This can be closed now.
