### ISSUE TITLE
Spike: Investigate IaC network tester for network testing/monitoring

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1055]
## User Story

Following on from the testing meeting - https://docs.google.com/document/d/1WTLqsA1XUtahLnif42A1vGyMg7-284z-c4MllZj4GT0/edit

We want to look further into this tool and if it would add value to the platform testing or monitoring.

https://github.com/aws-samples/aws-iac-network-tester

## Value

Improve our network testing/monitoring

## Definition of done

- [ ] investigation completed
- [ ] outcomes presented to the team
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sobostion** [comment]
Managed to get the tool up and running in core-sandbox with some example infrastructure to test on.

I think the bottom line is that in its current state in the repo, the step function it uses has a step that is too specific to CloudFormation. We may be able to fork the repo and re-write the `retrieve_path_to_test/app.py` lambda function to generalise it, by passing in the list of routes instead of the stack name and output key.

The tool can only test 5 routes at a time due to a limitation in VPC Reachability Analyser, but when testing in core-sandbox I found it takes around a second for it to complete the step function, so this shouldn't be a problem if we have multiple tests.

**Comment by sobostion** [comment]
A better alternative I have found is to replace the whole if-else section in the lambda handler of `retrieve_path_to_test/app.py` with one line: `allRoutes = event['allroutes']`

Then you can specify the route in a json block when you trigger the step function:

`aws-vault exec sandbox -- aws stepfunctions start-execution --state-machine-arn $state_machine_arn --input $input`

where input is the json file containing the routes (see attached for example).
[step_input.txt](https://github.com/ministryofjustice/modernisation-platform/files/7162335/step_input.txt)

**Comment by sobostion** [comment]
It looks like the step function actually iterates through batches of 5 rather than failing after 5 (unsure why it failed with 6 previously but it has now run successfully with 8). Therefore we shouldn't actually need a higher quota, and can use the one state machine for all of the routes we need to test.

**Comment by sobostion** [comment]
I think we know enough now that we can use this tool if there is a use case that appears in the future - however, looking at our current architecture, the limitation of only being able to test within a VPC means that there doesn't appear to be many resources that we can test with this currently.

I think we should close this for now given the above.
