### ISSUE TITLE
Spike: Investigate route table analyzer for network testing/monitoring

### ISSUE THREAD

**Issue by adeweetman-al** [ministryofjustice/modernisation-platform#1056]
## User Story

Following on from the testing meeting - https://docs.google.com/document/d/1WTLqsA1XUtahLnif42A1vGyMg7-284z-c4MllZj4GT0/edit

We want to look further into this tool and if it would add value to the platform testing or monitoring.

https://docs.aws.amazon.com/vpc/latest/tgw/route-analyzer.html

## Value

Improve our network testing/monitoring

## Definition of done

- [ ] investigation completed
- [ ] outcomes presented to the team
- [ ] any tickets for future work created
 
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pete-j-g** [comment]
The tool appears to be designed for diagnostics/troubleshooting rather than regular testing. Functionality and hypothetical use-case scenarios are described here:
- https://docs.aws.amazon.com/vpc/latest/tgw/route-analyzer.html
- https://aws.amazon.com/blogs/networking-and-content-delivery/advanced-troubleshooting-with-aws-transit-gateway-network-manager-route-analyzer/
- https://aws.amazon.com/blogs/networking-and-content-delivery/diagnosing-traffic-disruption-using-aws-transit-gateway-network-manager-route-analyzer/

In my opinion, the use-case scenarios do not match ours. Additionally, I was unable to find any documentation about accessing the tool programatically.

One way I think we could use the tool for testing, would be to have a periodically reviewed list of example sources and destinations we expect to work. Those would be grouped so that when a networking change is performed, an engineer would be able to identify a relevant group and test if their change did not negatively impact the network.
