### ISSUE TITLE
Delete dex-ta environment

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1467]
## User Story

Request from Ian to delete the environment, the contract was renewed and this is no longer needed.

## Definition of done

- [ ] environment deleted
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
$ aws-vault exec modernisation-platform -- terraform state rm 'module.environments.aws_organizations_organizational_unit.applications["dex-ta"]'
Removed module.environments.aws_organizations_organizational_unit.applications["dex-ta"]
Successfully removed 1 resource instance(s).

**Comment by SteveLinden** [comment]
Went through each of these directories but had to switch workspace to default before running the commandmodernisation-platform/terraform/environments/bootstrap/delegate-access

modernisation-platform/terraform/environments/bootstrap/secure-baselines

modernisation-platform/terraform/environments/bootstrap/single-sign-on

modernisation-platform/terraform/environments/dex-ta

modernisation-platform-environments/terraform/environments/dex-ta

For each I got the warning as shown


$ aws-vault exec modernisation-platform -- terraform workspace select default
Switched to workspace "default".
$ aws-vault exec modernisation-platform -- terraform workspace delete -force dex-ta-development
Deleted workspace "dex-ta-development"!
**WARNING: "dex-ta-development" was non-empty.
The resources managed by the deleted workspace may still exist,
but are no longer manageable by Terraform since the state has
been deleted.**

**Comment by SteveLinden** [comment]
Followed https://user-guide.modernisation-platform.service.justice.gov.uk/team-guide/deleting-an-environment.html#find-and-delete-the-terraform-workspaces-for-the-environment

**Comment by SteveLinden** [comment]
Merges undertaken. dex-ta-development still shows on the app list so investigating.
