### ISSUE TITLE
Analysis of risks around route53 and potential solutions

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1711]
## User Story

As an MP engineer, I need to understand the risk around shared access to route53, and what are the potential solutions to mitigate this risk vs the inconvenience to users.

## User Type(s)

MP engineers and MP users

## Value

More secure platform

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
We've discussed this in our threat modelling sessions; we believe that the risk here is minimal due to R53 rejecting attempts to create a duplicate entry and have this as part of our risk register reviews.
Will update this issue prior to closing with outcome of light-touch investigation / review of risk register.
