### ISSUE TITLE
Change core platform to use OIDC instead of credentials for security account

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2040]
## User Story

This ticket needs to be broken down in to the following - 

1. Create OIDC provider using the module
2. Update each terraform in the core repo to: 
3. ensure the action can assume the required roles
4. Update providers if needed
5. update the workflow file
6. test pipeline and locally running

## Definition of done

- [ ] OIDC providers created in core accounts
- [ ] Workflow files updated to use OIDC
- [ ] Terraform updated if needed to assume different roles in providers
- [ ] Create any roles if needed
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/1975

**Comment by julialawrence** [comment]
Using a different approach from the environments: one OIDC provider in modernisation platform account with the same permissions as the main ci user which will assume roles in core accounts. Alternative required either a different provider configuration for local plans/applies (not really viable) or substantial reworking of the IAM components in core accounts and main MP account. 

Single OIDC provider also simplifies the conversion substantially for core accounts. Requires no terraform code changes in the core accounts, just refactoring the workflow files to use OIDC.

Relevant PRs: 

https://github.com/ministryofjustice/modernisation-platform/pull/2392 (and the fix: https://github.com/ministryofjustice/modernisation-platform/pull/2393) for adding OIDC provider and refactoring core security workflow.

https://github.com/ministryofjustice/modernisation-platform/pull/2386 for adding MP environment secret to MP repo.

OIDC module:

https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/8 -- fixing go tests

https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/9 -- Adding managed policies var in order to configure the github-actions role with similar permissions to the ci user.
