### ISSUE TITLE
Testing-test overwrites tfstate used in new account creation process

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2086]
## Expected Behavior

The `testing-test` account should not interact with the `terraform.tfstate` file in the `modernisation-platform-terraform-state`S3 bucket

## Actual Behavior

Looking at the historical versions of the tfstate file, it appears that it is being overwritten when `testing-test` runs.
The overwritten `terraform.tfstate` cannot be interacted with by the New Environment process, causing the `Delegate Access` step to fail with an error similar to the following:

```
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: XZWK653V7CJVH0F2, host id: sYWt3VF6xgef62dCC4uZ4WM8INQpxdSDo5sAPxwVhAovwU6YiPgsI2UshKlQ+WD2qBOkHfqoNvaQD15ogL/3Pw==
Error: Process completed with exit code 1.
```

## Steps to Reproduce the Problem

  1. Make use of the `testing-test` account to run a unit test
  1. Observe that the `terraform.tfstate` object has changed in the `modernisation-platform-terraform-state` bucket
  1. Attempt to create a new environment by creating a new template such as `environments/bug-investigation.json`
  2. Observe that the `delegate-access` step in the `Terraform: New environment` workflow is unsuccessful

## Other information

Previous examples of this error can be seen in the Github actions that ran to create the `apex-development` environment, and by comparing the s3 object versions in the state bucket.

**Comment by davidkelliott** [comment]
Looking into this is appears that somehow the top level folder was used by a test, rather than the lower levels.  To prevent this from happening again we removed the permission to edit this file for the testing user.

Fixed with https://github.com/ministryofjustice/modernisation-platform/pull/2096

Tested running the tests for the S3 module locally an on the pipeline, neither caused updates to the tfstate.tf file and both ran successfully.
