### ISSUE TITLE
Code formatter causes PRs to be stuck as OPA tests haven't run

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2259]
## Expected Behavior

Code formatter should run and push formatting changes to the PR, this should trigger OPA tests to run again (or not dismiss the previous run)

Where else can the code formatter live? Pre commit? On a schedule?

## Actual Behavior

The push by the code formatter does not trigger any workflows to run.
This leads PRs to getting stuck and the only solution is to close and open the PR or push to it again with formatting already done locally.

## Steps to Reproduce the Problem

  1. Raise a PR with formatting issues
  1. Code fomatter runs and pushes to the PR
  1. OPA tests doesn't run and PR gets stuck

## Other information

This is a "feature" of github actions that jobs pushing to a PR don't trigger other jobs again. We need to look if there is a way around this or if we should handle formatting differently.

**Comment by davidkelliott** [comment]
We discussed a couple of potential fixes for this before - 

Running a pre commit code formatting lint - fine for us but more work for our users to install.

Don't run the code formatter on PR creation.  Run it once a night/weekly to create a formatting PR which we review and merge in daily/weekly.

That way it doesn't affect anyone, solves the problem and we still get formatted code in the repo.

**Comment by dms1981** [comment]
My first pass on this lead me to believe the the problem was down to a deliberate decision to stop `GITHUB_TOKEN` from causing recursive workflow runs: [Triggering an action](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#:~:text=When%20you%20use,push%20events%20occur.)

However, on trying to change to use a personal access token value, the same behaviour persisted: https://github.com/ministryofjustice/modernisation-platform/pull/3048/checks

After viewing a discussion that seemed relevant [here](https://github.com/orgs/community/discussions/26220) I trialled using a change to how credentials persist for the checkout action, but again this didn't change things, so my intention is to raise a support ticket with GitHub support to discuss this.

**Comment by dms1981** [comment]
Raised a ticket here: https://support.github.com/ticket/enterprise/83/1995251

**Comment by dms1981** [comment]
Philosophically, I like the approach of treating this in a similar fashion to dependabot requests, running an automated workflow task that checks out the repository and runs `terraform fmt --recursive` then pushes the diffs into a pull request.

A second option could be to include `terraform fmt --check` in the workflow for pull requests when we execute a terraform plan so that only well-linted code is committed in the first place

**Comment by dms1981** [comment]
You can see my proposed replacement here: https://github.com/ministryofjustice/modernisation-platform/compare/main...feature/2259-run-formatter-on-schedule

**Comment by dms1981** [comment]
Having run the code formatter, it needs a bit of finessing - it runs a lot of linters, and not all of them are appropriate for us. We'll evaluate this as a team.

**Comment by dms1981** [comment]
This will be resolved by https://github.com/ministryofjustice/modernisation-platform/pull/3145

**Comment by dms1981** [comment]
Reopened as there still seem to be some issues with committing the linter fixes

**Comment by dms1981** [comment]
The state of this at the start of sprint 43 is as follows:
We have a new action that runs on a nightly basis here: https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/format-code.yml
What ought to happen is that when the formatter runs, at the end of the run a new PR is raised with the re-linted code in it. However, when the action runs it doesn't _quite_ do what we want - the git action doesn't detect any changes as seen here: https://github.com/ministryofjustice/modernisation-platform/actions/runs/4350756229/jobs/7601760208
