### ISSUE TITLE
Spike: Ability to store secrets which aren't then destroyed on TF destroy

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3934]
## User Story

As an MP user
I want to be able to store longer lived secrets that I might not control
So that when I destroy my Terraform I don't have to put them in again

## User Type(s)

MP user

## Value

Helps prevent storing of secrets locally and reduces admin of having to re-input secrets regularly if doing regular destroys

## Definition of done

- [x] Spike complete and findings presented to the team
- [x] Issues created if we decide to take forward
- [x] another team member has reviewed
- [x] tests are green
- [x] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Researching...

Terraform documentation states you can add a 
+ lifecycle {
+   prevent_destroy = true
+ }

to prevent destruction but this will just display an error on a terraform destroy command

**Comment by SteveLinden** [comment]
The above will cause the terraform destroy to fail and, therefore, prevent it from working as required.
Looking at other options which appear to be slim (or none)

**Comment by SteveLinden** [comment]
One thing to remember is that the secret is not immediately destroyed so it can be manually restored UNLESS the code contains recovery_window_in_days=0 which should enforce immediate deletion.

**Comment by SteveLinden** [comment]
There is a lifecycle step called "prevent_destroy"  which can be set to true (prevent_destroy = true) which will also stop something being destroyed but, again, this will result in the terraform destroy erroring out and failing.

**Comment by SteveLinden** [comment]
Another option is to remove the item from the state file BUT I WOULD NOT SUGGEST THIS IS USED. Included here for reference

One option here is to tell Terraform to “forget about” this object, which will sever the binding between the object in the remote system and this block in your configuration. The object will continue to exist but Terraform will no longer have any record of it, and so terraform destroy will not propose to delete it.

_terraform state rm kubernetes_config_map.aws_auth_
When doing this, beware that it’s a one-way operation: once Terraform has “forgotten” this object it becomes the same as any other object in the remote system that this Terraform configuration didn’t create, and so if you want to re-bind it to the same address you will need to import it again.

**Comment by SteveLinden** [comment]
OK. I tested this in example after removing the recovery_window_in_days=0.

Build example (everything rather than just one thing) and checked the secret. It was there - example-db-password.

I then destroyed example (again everything) and checked - the secret was marked as to be destroyed.
I went into the secrets manager and listed to include all scheduled for deletion. When I picked this I could then access the 
Cancel deletion button. I selected that, then confirmed I wanted to cancel the deletion and it was cancelled. To confirm I then unchecked the ¬Show secrets scheduled for deletion¬ checkbox and it was still there.

**Comment by SteveLinden** [comment]
The repeated process with the recovery window flag set resulted in the secret being immediately removed. It does not even appear in the list of secrets scheduled for deletion it had been completely removed.

**Comment by SteveLinden** [comment]
My, current based on the current terraform model 

1. remove the  recovery_window_in_days = 0 from all terraform processes. This will only impact 6 current environments.
2. if a secret is needed to be in place then follow the process above to cancel the deletion from the console.
3. if a secret should be immediately removed follow the process above using the delete-secret from aws. You will need to ensure that the "Set AWS environment variables (Short-term credentials)" is run first.

At present, other than throwing an error on destroy, there seems to be no process in place to stop terraform from removing items in a destroy.

**Comment by SteveLinden** [comment]
Some suggestions were put forward about other options such as moving where the secrets are created. I thought about this and if we wanted to remove the secrets an additional run would be needed to do this. If we wanted to keep the secrets there would be no issue.
If the secrets are to be kept the code would also need to be changed to remove the step which builds the secret otherwise the rebuild will fail.
I'll have a think about other options but the above one seems to be the most appropriate. Once a build gets moved to production and no destroys are needed this is likely not an issue.

**Comment by SteveLinden** [comment]
The other alternative is to move all secret create statements to the modernisation-platform repo rather than the modernisation-platform-environments repo. If a destroy is run on the environment side it would not impact the secret. This will involve more work in moving the items to the modernisation-platform folder.

**Comment by SteveLinden** [comment]
So the two main options are 

1. Option 1 above - remove the recovery_window_in_days = 0 from code and cancel the deletion from the console if the secret is needed
2. Build the secrets code in another repo so that it does not automatically get deleted if destroy is run. This would require additional work to "move" the secret code so is maybe an option for newer code

**Comment by SteveLinden** [comment]
Preferred option is the second one. Look at https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-resources.html#next-steps for information but it should go in the modernisation-platform repository.
