### ISSUE TITLE
MLRA go live check list

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#4948]
## User Story

As a modernisation platform engineer
I need to be confident that I have all the information I need for supporting new applications as they go live
So that I can effectively provide support.
Details are provided here:
https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html

## User Type(s)

MP engineers

## Value

Ensure code quality and security of the platform

## Definition of done

- [ ] checklist udpated
- [ ] reviewed by another team member

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Contacted Mike Reid and he said that this will be included in their next sprint. I will put this in blocked until we get those details.

**Comment by SteveLinden** [comment]
Ticket to track progress on the LAA side
https://dsdmoj.atlassian.net/jira/software/c/projects/LAWS/boards/262/backlog?selectedIssue=LAWS-3529

**Comment by SteveLinden** [comment]
This may have been completed now based on a slack message from Mike Reid. Their ticket contains the following

"Application is not public facing with ingress filtered via WAFv1 ACL.

EC2 uses AL2 AMI with SSM installed.

Infra-code. Known issues that cannot be resolved quickly as its a prod system & so will notify MP of them. Namely:

Use of parameter store for one secret.

DB password secret cannot be cycled as we don't own the source secret.

Cloudfront Token doesn't cycle & cannot without investigation that it can.

README has been updated & reviewed with product team.

Technical & Security Guidance. The infrastructure is based on an existing implementation dating back to mid 2018 rather than a new design.

Testing & Go-Live. Application is already live & was thoroughly tested beforehand.

Monitoring & Alerting in place using PagerDuty & Slack

Product team contact details in the README. (slack team name)

Application went live in MP at the end of August 2023."


Additionally Mike says
"Each of those points aligns to each point of the check list."

**Comment by SteveLinden** [comment]
Plan is to copy the details above and put them somewhere safe so we have a copy of the release details.

**Comment by SteveLinden** [comment]
The secrets.tf file is currently empty which may help resolve the secrest issues that are mentioned above but other than that the code looks fine.

**Comment by SteveLinden** [comment]
Slack message from Mike Reid
https://mojdt.slack.com/archives/DU3MD0865/p1699364275732629
