### ISSUE TITLE
✨ Introduce custom schedules to `modernisation-platform-instance-scheduler`

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#5302]
### User Story

As a Modernisation Platform Customer
I want to set custom start and stop times for my instances through AWS tags
So that I can control when they are started or stopped

### Value / Purpose

Customers will, on occasion, need to step outside of our pre-defined windows for starting and stopping EC2 or RDS instances. While they can be exempted from scheduling by way of setting `instance-scheduling/skip-scheduling`, there is no way to set custom stop or start times.

Customers may also need to stagger the start times of their instances. Having the ability to set a tag containing, perhaps, a `cron` value, would allow them to meet this need while balancing our responsibility to run a sustainable platform.

### Definition of Done

- [ ] User research conducted
- [ ] Tests written for proposed changes
- [ ] Code written for proposed changes
- [ ] Custom start/stop times tested
- [ ] New module version released

**Comment by connormaglynn** [comment]
@ewastempel suggested a way forward for this work that seems like a simpler way of executing the scheduler process (details in this [thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1712221455468869))

## The AS IS Process and The Problem
The current process relies on several AWS components to implement instance scheduling for the entire MP estate (high-level diagram below 👇 )

![Image](https://github.com/ministryofjustice/modernisation-platform/assets/66882795/606634e8-e690-4c68-b246-3701ccc7bef0)

Letting customers define custom schedules is difficult due to it's top-down nature, the schedule is defined in one place and all other accounts inherit that time.

## Options

**Option 1: Run The Job More Often**

We could simply run the job more often, define more schedules at the top and an extra tag to instances that customers can use to define which time they would like.

This approach is simple and fits with the current infrastructure - although it does feel fairly wasteful, constantly polling for this information that may not be used. And our schedules may not fully align with our customers' needs

**Option 2:  Allow Customers to Create The Current Infrastructure in Their Accounts**

This would mean refactoring the way the current code ways, to add a module that the customer could easily use in their infrastructure to rebuild the same functionality locally

This approach gives the customer additional controls over when schedules are ran and potentially other variables in the process - but does require the customer to be responsible for additional infrastructure

**Option 3:  Create a Re-useable GitHub Action (thought of by @ewastempel)**

This would mean implementing a new service of a re-usable GitHub action that essentially re-implements the current functionality we have in the Lamda Function.

This approach gives the customer the same additional controls as option 2, without the burden of additional infrastructure. 

We currently have the infrastructure to support allowing application repositories to access their accounts instances (with some potential tweaks).

## Decision

I favour option 3 - it lowers the amount of infrastructure and can be easily built, tested and shipped without impacting current systems
