### ISSUE TITLE
State locking is not happening for the tf state of environments.

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#5534]
### Expected Behavior

The state should be locked when one pipeline runs to prevent other sources from modifying it during the original pipeline execution.

### Actual Behavior

Multiple pipelines run in parallel in environments result in tf state being modified by multiple sources at once.

See this slack thread [slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1700222597056929) for more details.

### Steps to Reproduce the Problem

See this slack thread [slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1700222597056929) for more details.
See the issue that implemented it in the modernisation-platform repo: https://github.com/ministryofjustice/modernisation-platform/issues/2467
See this [slack thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1677155316096599?thread_ts=1677151518.406999&cid=C013RM6MFFW) to understand why it could not be implemented at the time.

### Modules

modernisation-platform-environments repository

### Account

all environment accounts

**Comment by dms1981** [comment]
As a quick summary of what's been done:
* A new role with a scoped policy - `modernisation-account-terraform-state--member-access` has been created.
* This role can be assumed by the Github Actions role, and the Modernisation Platform Developer role.
* This role has been tested locally, and through GitHub actions. You can see an example of a run failing due to a mismatched lock ID [here](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/7130680774/attempts/1).
* A PR that amends the `reusable_terraform_plan_apply` job and configures back end state locking has been raised [here](https://github.com/ministryofjustice/modernisation-platform-environments/pull/4254).

**Comment by dms1981** [comment]
On my to-do list are the following:

- [ ] Finalise the PR for `modernisation-platform-environments`
- [ ] Conduct some further testing, ideally with someone who's not been part of this work to get a fresh view
- [ ] Inform our customers
- [ ] Create a corresponding PR in `modernisation-platform` that updates the templates and our documentation
