### ISSUE TITLE
SPIKE: NCSC: Logging and Monitoring - best practice

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6735]
### User Story

Following review with NCSC they have made the following recommendations

>#### Logging and Monitoring
>The platform captures the following log data: VPC Flow Logs, Firewall Logs, CloudWatch Logs. Currently, log data is stored but no ongoing analysis is performed.
>
>**Risk:** A compromise of the platform is unlikely to be detected as analysis is not performed on log data. 
>
>**Recommendation:** Consider the following NCSC guidance. 
https://www.ncsc.gov.uk/blog-post/what-exactly-should-we-be-logging
https://www.ncsc.gov.uk/collection/building-a-security-operations-centre

The second document might lead to recommendations to SOC team

Also make any other suggestions for improvement

MoJ Response: We will review this document as a separate ticket. 

This is to review the documentation and make recommendations

### Value / Purpose

to improve security within the platform

### Definition of Done

- [x] Document reviewed and recommendations made
- [ ] Agreement on which recommendations to implement and which to ignore - saying why we are ignoring them
- [ ] If required, raise tickets to implement any new changes

**Comment by dms1981** [comment]
For the most part, the recommendations on what logs to keep have already been met and those logs are shipped to our SOC-PM team's tool of choice. I'll expand on my thoughts on the recommendations themselves in a following comment.

**Comment by dms1981** [comment]
**1. Reconnaissance**:

From a platform perspective we would surface this information from VPC flow logs showing attempts against public-facing interfaces (eg. load balancers or elastic IPs). Things like simple port scans should be visible here. Other methods such as checking applications for available endpoints - `my-application.service.justice.gov.uk/api` for example - would be in the domain of an application support team and not a platform-level thing. We're deliberately very open with how we work so reconnaissance for the platform would be as simple as browsing our repositories.

**2. Resource Development**

Hard to say but the givenI don't think example here we do rely heavily on GitHub for authentication and to my knowledge we're good at keeping login credentials fresh (revoking / suspending accounts and access keys, using OIDC and SSO for logins). Potentially we need to consider how our DNS records are secured through DNSSEC but I think that's a bigger question than just us and should be considered for the `justice.gov.uk` and `service.justice.gov.uk` domains (https://dnssec-debugger.verisignlabs.com/modernisation-platform.service.justice.gov.uk).

**3. Gaining Initial Access**

Mostly we'd expect to see attempts - failed or successful - through CloudTrail logs. We do rely on other services (and could view logs in Auth0 for example) but we're consumers of these things. For application-specific logs we don't have sight, nor would we expect to. The guidance here is quite broad - an enterprise campus for example. Our points of access are all public API endpoints. We mitigate the risk of personal compromise with mandated 2FA, so again I'm not sure what we would need to look at that isn't in our risk register.

**Comment by dms1981** [comment]
**4. Execution of Attacker controlled code**

From a _platform_ perspective the obvious route here is that a GitHub repository containing Terraform code is compromised but we mitigate this through the use of source code hashes to pin our versions. A supply chain attack isn't highly likely but is conceivable yet not something we could meaningful do - for example if we span up a parallel infrastructure to archive Hashicorp terraform provider versions, is it likely that we'd discover compromised code before anyone else and thus stay away from a compromised version?

**5. Persistence**

I don't think there's much relevance here. Given that the source of truth for the platform is infrastructure as code we're not exposed in the way that an enterprise could be by having a malicious application existing on its internal network.

**6. Privilege escalation**

We've discussed this in our platform risk register. I don't see this a high risk for us. We use SSO for login and control trust chains through IAM policies - there aren't options for privilege escalation that exist outside of misconfigured IAM policy. If there are, then they exist outside of our platform or ability to influence.

**7. Defence evasion**

The guidance here reads as very application focused - an application running on the platform rather than the platform itself. For us the risk would be supply chain focused; the AWS CLI or Terraform (and provided plugins) but this should be easily mitigatable by checking against publised secure hash values.

**Comment by dms1981** [comment]
**8. Credential access**

I think this is reasonably defended against (SSO & 2FA), and as we log access attempts in CloudTrail (and then ship those logs to SIEM) then there's not much more I can think of for us to do. We also expire users and access/secret keys after reasonable periods of non-use so the risk of stale credentials being used is low.

**9. Discovery**

On this topic we're extremely discoverable by design. If we can make something open we have done so (user guidance and runbooks, documentation, diagrams, code). This is something across the wider GDD/Justice Digital landscape - https://mojdigital.blog.gov.uk/2017/02/21/why-we-code-in-the-open/. We do keep some things defended (application secrets, tokens) and these should be rotated anyhow in case they're leaked. We have also reviewed our logs and improved our masking to prevent accidental disclosure.

**10. Lateral movement**

On a platform level we mitigate against this for our customers by design (no movement between `live_data/non_live_data`), but they also have to take reasonable steps to mitigate (EG with correctly configured security groups). This information (failed attempts to assume a role for example) should also be covered by CloudTrail logs and shipped to SIEM.

**Comment by dms1981** [comment]
**11. Collection**

As a platform we don't really hold anything that this advisory would cover; internal code artefacts for example or sensitive design documents. Potentially customer S3 buckets could be in scope, but those are private by default and should be the subject of a Security Hub /Guard Duty alert if they're improperly secured (https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_finding-types-s3.html#policy-s3-bucketpublicaccessgranted).

**12. Command and control**

This feels like a potential risk for applications rather than the platform itself (EG. hijacking an instance and using it to serve traffic), but I don't think the risk here is high given how traffic flows are controlled through different layers of protections (AWS-provided, NACLs, SGs, Network Firewall scanning of traffic going from platform to internet). With regard potential malicious domains we do supply Route53 resolver logs to SIEM for scanning.

**13. Exfiltration**

As noted above, we don't really have anything that's at risk of exfiltration. We have everything out in the open where possible and don't hold anything sensitive beyond application secrets and tokens. Those can be revoked & regenerated, and their compromise is hard to leverage outside of a bigger compromise.

**Comment by dms1981** [comment]
I will add a following comment summing up potential actions but I don't expect there will be anything that's not already in our risk register.

**Comment by dms1981** [comment]
As a follow-up, there are no obvious platform-specific actions that stand out to me after reviewing the guidance. Our CloudTrail logs are probably the most interesting thing we hold for security audit purposes, and those are shipped off to the Security Operations Monitoring - Protective Monitoring team through a kinesis firehose connection. Beyond that we supply our VPC flow logs, firewall logs, and Route53 resolver logs to provide visibility of customer applications deployed on the Modernisation Platform.
