### ISSUE TITLE
New environments for CWA

### ISSUE THREAD

**Issue by vc13837** [ministryofjustice/modernisation-platform#6866]
### Environment details

There are 5 environments currently for this application and we are in the process of understanding whether one of them can be removed. If this is not possible, are we allowed to have 5 environments in MP?

### Application Name

contract-work-administration

### Description of application

CWA is the application used by:

- Providers to submit their bills and view their contracts and schedules
- Contract management to upload contracts and schedules
- To hold and update all provider contact details and user management for LAA

### GitHub team slug

laa-aws-infrastructure

### GitHub code owner team slug

laa-aws-infrastructure

### GitHub actions reviewer team slug

laa-aws-infrastructure

### Environments

- [X] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

Contract & Work Administration

### business-unit

LAA

### infrastructure-support

laa_ops@digital.justice.gov.uk

### owner

laa_ops@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [x] Other - please specify - Bastion access is required due to the age of the operating system.

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by davidkelliott** [comment]
Hi @vc13837 we cannot provide 5 separate environments for an application, however if additional environments are needed they can be implemented within a current environment, for example if you need an additional environment for training, servers could be stood up inside the testing or preproduction accounts depending on the data, by creating additional conditional EC2s in that account or using a terraform count on the existing resources which conditionally increases in certain environments. Some teams have put their server code into modules so that they can easily stand up multiple servers in one account.

**Comment by SteveLinden** [comment]
Named the account contract-and-work-administration to avoid using "&".

**Comment by SteveLinden** [comment]
I will email this information and access to our user guides to the address above.
