### ISSUE TITLE
Review sandbox nuke skips

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#6922]
### User Story

As a mp engineer
I expect teams to not skip the sandbox nuke unless absolutely necessary
So that old resources not in code are cleaned up

### Value / Purpose

Ensure nuke runs in sandbox environments to keep them clean and save money and carbon by destroying unused resources.

### Definition of Done

- [x] Nuke skips reviewed
- [x] Teams contacted to confirm if skip can be removed

**Comment by mikereiddigital** [comment]
The following sandbox environments are excluded from nuke:

`analytical-platform-compute.json:          "nuke": "exclude"
analytical-platform-ingestion.json:          "nuke": "exclude"
ccms-ebs-upgrade.json:          "nuke": "exclude"
ccms-ebs.json:          "nuke": "exclude"
cica-copilot.json:          "nuke": "exclude"
corporate-staff-rostering.json:          "nuke": "exclude"
data-and-insights-wepi.json:          "nuke": "exclude"
data-platform-apps-and-tools.json:          "nuke": "exclude"
data-platform-apps-and-tools.json:          "nuke": "exclude"
data-platform-apps-and-tools.json:          "nuke": "exclude"
data-platform-compute.json:          "nuke": "exclude"
data-platform-compute.json:          "nuke": "exclude"
data-platform.json:          "nuke": "exclude"
data-platform.json:          "nuke": "exclude"
delius-core.json:          "nuke": "exclude"
delius-core.json:          "nuke": "exclude"
delius-jitbit.json:          "nuke": "exclude"
delius-mis.json:          "nuke": "exclude"
delius-nextcloud.json:          "nuke": "exclude"
digital-prison-reporting.json:          "nuke": "exclude"
electronic-monitoring-data.json:          "nuke": "exclude"
electronic-monitoring-data.json:          "nuke": "exclude"
hmpps-domain-services.json:          "nuke": "exclude"
hmpps-oem.json:          "nuke": "exclude"
laa-ccms-infra-azure-ad-sso.json:          "nuke": "exclude"
laa-oem.json:          "nuke": "exclude"
nomis-combined-reporting.json:          "nuke": "exclude"
oasys-national-reporting.json:          "nuke": "exclude"
oasys.json:          "nuke": "exclude"
planetfm.json:          "nuke": "exclude"
portal.json:          "nuke": "exclude"`

**Comment by mikereiddigital** [comment]
All of the following environment files have nuke exclude defined.

analytical-platform-compute.json
analytical-platform-ingestion.json
ccms-ebs-upgrade.json
ccms-ebs.json
cica-copilot.json
corporate-staff-rostering.json
data-and-insights-wepi.json
data-platform-apps-and-tools.json
data-platform-compute.json
data-platform.json
delius-core.json
delius-jitbit.json
delius-mis.json
delius-nextcloud.json
digital-prison-reporting.json
electronic-monitoring-data.json
hmpps-domain-services.json
hmpps-oem.json
laa-ccms-infra-azure-ad-sso.json
laa-oem.json
nomis-combined-reporting.json
oasys-national-reporting.json
oasys.json
planetfm.json
portal.json

**Comment by mikereiddigital** [comment]
Confirmed that it is the account-level exclude rather than any resource-specific rules. These are the accounts in scope:

analytical-platform-compute.json
analytical-platform-ingestion.json
ccms-ebs-upgrade.json
ccms-ebs.json
cica-copilot.json
corporate-staff-rostering.json
data-and-insights-wepi.json
data-platform-apps-and-tools.json
data-platform-compute.json
data-platform.json
delius-core.json
delius-jitbit.json
delius-mis.json
delius-nextcloud.json
digital-prison-reporting.json
electronic-monitoring-data.json
hmpps-domain-services.json
hmpps-oem.json
laa-ccms-infra-azure-ad-sso.json
laa-oem.json
nomis-combined-reporting.json
oasys-national-reporting.json
oasys.json
planetfm.json
portal.json

**Comment by mikereiddigital** [comment]
Emails sent to the above contacts for the environments in scope.

**Comment by mikereiddigital** [comment]
Updates here - https://docs.google.com/spreadsheets/d/1DxmAWk5lecuBNq8Bu3IyvlWY0p2lrDxYHPERS-CCKiQ/edit?usp=sharing

**Comment by mikereiddigital** [comment]
Most have responded but following up with those who have not yet responded or who the listed contact is no longer correct.

**Comment by mikereiddigital** [comment]
Chat with William Rose regarding the data-insights-wepi environments on Thursday at 11am.

**Comment by mikereiddigital** [comment]
Call with Will Rose raised the possibility that the environment could be deleted. The PM/DM is back from maternity leave towards the end of June so will set up another meeting for then which will confirm matters.

Also not heard from Adedotun Adenipekun since the call earlier in the week & so will chase again.

**Comment by mikereiddigital** [comment]
Moving to done as no further action can be taken.
