### ISSUE TITLE
Further investigation/resolution of TLS below version 1.2

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7183]
### User Story

This is a follow up to ticket - https://github.com/ministryofjustice/modernisation-platform-security/issues/4

Although we now have fewer alerts for TLS 1.0 and 1.1we still have some.

This ticket to look at the remaining issues and either resolve them, where it is our responsibility or to highlight them to the appropriate team (and also to pass those teams on to TVMSOC (John Lillington)
The items are in the attached

## Useful Information
John Lillington should be the recipient of information; they can be contacted via Slack

### Value / Purpose

Insecure versions of the TLS protocol, such as TLS 1.0 and TLS 1.1, have been deprecated by the Internet Engineering Task Force (IETF) as of March 25, 2021. These versions lack support for current and recommended cryptographic algorithms and mechanisms. This ticket is to ensure we remain compliant

### Useful Contacts

John Lillington

### Definition of Done

- [x] Identify accounts where versions below `1.2` are in use across Modernisation Platform
- [ ] Request teams remediate this to have `1.2` as the minimum version
- [ ] Inform SOC team about exceptions where lower versions are required
- [ ] Request another report to confirm the fix

**Comment by dms1981** [comment]
Contacted John Lillington via Slack to request an updated copy of the SOC outputs.

**Comment by dms1981** [comment]
~90% of the alerts are related to the `tribunals` application and will be solved by [this PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/6608).
For the handful of `portal` alerts, there are all in development and will be solved through this ticket: https://dsdmoj.atlassian.net/browse/LAWS-3910
Of the remainder related to `xhibit-portal` these and will not be fixed as the less-secure listeners are required due to infrastructure limitations.
For those belonging to `performance-hub-development` they have been resolved by [this PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/6619).

**Comment by dms1981** [comment]
Informed John via Slack of my findings / actions.
