### ISSUE TITLE
Add S3 mount for Performance Hub

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#721]
## User Story

Performance Hub needs to able to read and write too persistent storage from a container.

Design document needs to be updated to show the S3 mount.

## Value

Baseline requirement for the functioning of the app

## Definition of done

- [ ] design docs have been updated
- [ ] another team member has reviewed
- [ ] Update user data for ECS cluster server to install and configure rclone.
- [ ] Mount S3 bucket on all ECS hosts.
- [ ] Reconfigure ECS task definition so containers can see S3 mount point. 
- [ ] Log into container instance and verify that you can see the s3 bucket, and that you can read and write from it.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ezman** [comment]
Originally we were going to use Amazon's EFx File Service to build this capability. Unfortunately EFx requires a domain control to either exist somewhere on the network, or one can be created specifically for managing access. This add extra cost and complication, so we are going back to S3. We need to find a free tool that lets us mount S3 buckets as a file system mount, basically like s3fs on Linux.

**Comment by ezman** [comment]
We are now code complete on this feature, however there is an issue around Windows credentials which means we can't automate the final stage, because we have a chicken and egg situation because of the Windows password not being known when the bootstrap code runs.

For now we are going to keep the manual step and see if we can resolve this in the future.

**Comment by ezman** [comment]
We found another problem, Docker on ECS for security reasons does not support bind mounts to a separate volume. Which is why we have not been able to get the S3 mount to work. This means are only option is to go back to EFx or re-write the application code to use S3 natively. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html

_Windows containers can mount whole directories on the same drive as $env:ProgramData. _

Which means on sub-folder on the C drive can be used for bind mounts.
