### ISSUE TITLE
Unit Tests for Config module in Baselines

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7308]
### User Story

As a MP Engineer
I need to write some unit tests for the Config sub-module sin the Baselines module
So that I can increase the confidence in the modules

### Value / Purpose

As a follow-on from https://github.com/ministryofjustice/modernisation-platform/issues/6490 this ticket is to add missing unit tests for some of the sub-modules in the MP Baselines module.

There are roughly 29 resources for unit testing.

### Useful Contacts

@richgreen-moj

### Definition of Done

- [ ] Missing unit tests added
- [ ]  New unit tests pass
- [ ]  Another team member has reviewed

**Comment by Kudzai-moj** [comment]
This ticket is to be closed/added to firebreak.  We currently  cannot test this module because only one "aws_config_configuration_recorder" resource is allowed per region, and 26 other resources in the module depend on it. Inorder to do unit tests, we need to create duplicate resources and then delete them, but this cant happen if AWS only allows [one recorder](https://repost.aws/knowledge-center/config-max-recorders-error) per region.

**Comment by Kudzai-moj** [comment]
Had a discussion with Ed and Ewa and we agreed that either the ticket should be closed, or added to firebreak

Work was done on [this branch](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/tree/feature/7308-Unit-Tests-for-Config-module-in-Baselines)

We are getting the error,

"TestTerraformConfig 2024-08-20T09:07:04+01:00 retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: putting ConfigService Configuration Recorder (config-TxG6Ur): operation error Config Service: PutConfigurationRecorder, https response error StatusCode: 400, RequestID: 86d903f1-fcec-47cb-a1a3-618af5a439f1, MaxNumberOfConfigurationRecordersExceededException: Failed to put configuration recorder 'config-TxG6Ur' because the maximum number of configuration recorders: 1 is reached.
│ 
│   with module.config-test.aws_config_configuration_recorder.default,
│   on ../../modules/config/main.tf line 4, in resource "aws_config_configuration_recorder" "default":
│    4: resource "aws_config_configuration_recorder" "default" {"

**Comment by SimonPPledger** [comment]
We rarely change config and this is very difficult to test, so we will not do this work - closing
