### ISSUE TITLE
Test the effects of temporarily disabling a workflow

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7312]
### User Story

As a MP Engineer
I want to test the impact of temporarily disabling a workflow (e.g. New Environment workflow during account deletion process)
So I have confidence in using it for processes such as during account deletion

### Value / Purpose

Find out what happens when we temporarily disable a workflow. Specifically, what are the impacts on PRs which may be merged while the workflow is disabled and what happens once the action is enabled again?

### Useful Contacts

@richgreen-moj

### Additional Information

- https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow

- https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/deleting-an-environment.html#deleting-an-environment-aws-account

### Definition of Done

- [x] Agree on a workflow to suspend with team (e.g. New Environment)
- [x] Communicate with team while testing is in progress (reduce disruption etc.)
- [x] Merge some PRs that would trigger the workflow
- [x] Enable the workflow and review the effects (are there any conflicts?)
- [ ] If deemed suitable add step to the [delete accounts](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/deleting-an-environment.html#deleting-an-environment-aws-account) runbook

**Comment by Khatraf** [comment]
I’ve tested disabling the format code workflow and raised PRs with formatting errors as a manual run didn’t pick up on any changes and observed that it allows PRs to merge directly into the main branch, skipping any checks or tests the workflow would normally perform.   Once the workflow is re-enabled, it does not automatically process these PRs as it only triggers on new events.  
Also, GitHub Actions does not keep a backlog of past events to trigger upon re-enabling a workflow. So any PRs merged while the workflow was disabled will go untested unless manually triggered, creating gaps in validation and increasing the risk of introducing unchecked changes.  

Requires manual efforts to disable/enable workflows but also for validation to trigger the workflow and validate the code. In my opinion it’s not worth the effort of doing this for the purpose of deleting an environment. Disabling the new environment workflow would require stopping the associated checks, and instead, it would be more efficient to keep the workflow active and delay PR merging as we currently do and also we don’t really delete accounts very often.  

An ideal solution would be having something like a pause function that temporarily stops the workflow but queues up any events during this period. Once unpaused, the workflow would automatically process these pending events, ensuring that all necessary checks are applied without requiring manual intervention. However, since this functionality isn’t available I recommend keeping workflows enabled to maintain consistent automated checks and minimise risks of having PRs merged that bypass the checks we have in place.

**Comment by Khatraf** [comment]
I also tested an alternative approach by marking the workflow as a required status check in branch protections, which successfully prevents merges to main when the workflow is disabled. However, this method still requires manual intervention to trigger the workflow after re-enabling—such as reopening the PR or pushing an empty commit. 
![Image](https://github.com/user-attachments/assets/890c2af2-1d9a-4bee-9ce5-8f6b3e6c0805)

**Comment by richgreen-moj** [comment]
I've reviewed this ticket and chatted with @Khatraf about the pros and cons of the approach and agree that it is not worth pursuing this as a step in the account deletion process. We don't do deletions that often and the manual intervention required doesn't make the process any simpler.
