### ISSUE TITLE
Add Alias for bastion KMS key

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7569]
### User Story

As a MP user and engineer
I expect to be able to identify bastion KMS keys easily
So that I can see which keys are used for what

### Value / Purpose

There was recently some confusion with a user as to why KMS keys were being deleted.  Although the KMS key does have a name tag, it doesn't have an alias which means it's not immediately apparent as to which key it is in the console.  Adding an alias would make this clearer.

### Additional Information

https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/blob/main/main.tf#L59

It is probably worth adding a unique string to the name, as bastions can be deleted and created frequently as users create and destroy their Terraform and we don't want to get caught out with naming clashes.

### Definition of Done

- [x] Update bastion module to include alias for KMS keys
- [x] Update tests

**Comment by richgreen-moj** [comment]
@dms1981 - happy with the functionality updates and tests etc. applied to the module 👍 

I was just wondering about the release strategy. This has been put as a patch [v4.3.1](https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/releases/tag/v4.3.1) but it's not backwards compatible e.g. [this plan](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/11344970553/job/31550840954?pr=8251#step:11:1281) on a dependabot bump for the module on a member environment. I know you've explained the need for changes in the release notes though. Do you think it should be at least a `v4.4.0` or even a `v4.5.0`? 
(I might be overthinking it).

I don't think many members have upgraded past `v4.2.1` as it stands and since then we've had the `v4.3.0` AMI update too. That update though I think will work without any code changes.

**Comment by mikereiddigital** [comment]
I've reviewed this and am happy the ticket is complete.
