### ISSUE TITLE
Instance Scheduler - Cross-account access "AccessDenied" for certain accounts.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#8558]
### Expected Behavior

From core-shared-services, the instance scheduler lambda with the role InstanceSchedulerLambdaFunctionPolicy/instance-scheduler-lambda-function will attempt to assume the role InstanceSchedulerAccess in the member account. 

In addition, this error is not being tracked & logged in the lambda log. As such its hidden amongst the general unauthorised-api-alert errors and not flagged as an instance scheduler error.

### Actual Behavior

For some accounts an AccessDenied error occurs. Note that this error is not logged in the lambda log & does not show as an error in the lambda metric.

Examples of cloudtrail ids in core-shared-services showing this error are:

3b012434-a836-453c-9e14-983c00a0a662

4af4ceab-c294-4ce7-9878-ccb881dd2035

552a5917-5a17-4aa3-8dfc-48c9c4cefe7f

### Steps to Reproduce the Problem

These events can be found every morning & afternoon the instance scheduler runs.

Source code & module call can be found here - https://github.com/ministryofjustice/modernisation-platform/blob/11c18b77be7de8ad0e6c1cc574e70a9bc751417a/terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf#L1

### Account

core-shared-services

**Comment by sukeshreddyg** [comment]
I have reviewed the CloudTrail logs and found that the failure is due to the `InstanceSchedulerLambdaFunctionPolicy` role in core-shared-services being unable to assume the `InstanceSchedulerAccess` role in a couple of accounts. All the accounts where the assumption failed are related to `member-unrestricted` access. The `InstanceSchedulerAccess` role was created only for `member` accounts. If we create the `InstanceSchedulerAccess` role in the `member-unrestricted` accounts, it will resolve the issue.

**Comment by sukeshreddyg** [comment]
I have updated the Instance Scheduler skip list and the Lambda function with the latest AMI, which ran yesterday at 9 PM and today at 6 AM. I cannot see any errors related to the Instance Scheduler Lambda function failing due to being unauthorized to perform the assume role operation or AccessDenied errors due to the assume role.

**Comment by markgov** [comment]
work is complete and no errors are popping up

**Comment by sukeshreddyg** [comment]
No errors are popping up, I'm moving it to done!
