### ISSUE TITLE
create a local sandbox transit gateway

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#889]

**Comment by donmasters** [comment]
An issue has been identified due to the process of testing Transit Gateway peering using the Sandbox account.

**details**:
Transit Gateway peering of two Transit Gateways in the same region is not supported yet in London (eu-west-2).

**Comment by donmasters** [comment]
Reviewed Transit Gateway peering workaround using a routing VPC with two routing subnets.

The solution worked but had several reasons to justify it's use
- Complex routing due to the fact that the default route on Mod Plaformform is used for NAT gateway
- Increased cost of Transit Gateway connections
- Increased cost of Transit Gateway traffic
- This solution will have to be undone when AWS implement the Same Region Peering in Q4 2021

For the above reasons this solution has been parked for now, this can be implement if Transit Gateway Peering is urgently required.
